name: Deploy Frontend to VPS

on:
  push:
    branches:
      - development   # change if needed

jobs:
  build-and-deploy:
    runs-on: ubuntu-latest

    steps:
      # 1. Checkout code
      - name: Checkout code
        uses: actions/checkout@v3

      # 2. Setup Node
      - name: Setup Node
        uses: actions/setup-node@v3
        with:
          node-version: 20

      # 3. Install dependencies
      - name: Install dependencies
        run: npm install

      # 4. Build project
      - name: Build project
        run: npm run build

      # 5. Deploy to VPS via SSH
      - name: Deploy to VPS
        uses: appleboy/ssh-action@v1.0.3
        with:
          host: ${{ secrets.VPS_HOST }}
          username: ${{ secrets.VPS_USER }}
          key: ${{ secrets.VPS_SSH_KEY }}
          port: 22
          script: |
            rm -rf /var/www/shinelogics-frontend/*
      
      # 6. Copy build files to VPS
      - name: Copy files
        uses: appleboy/scp-action@v0.1.7
        with:
          host: ${{ secrets.VPS_HOST }}
          username: ${{ secrets.VPS_USER }}
          key: ${{ secrets.VPS_SSH_KEY }}
          source: "build/*"
          target: "/var/www/shinelogics-frontend"

      # 7. Restart nginx
      - name: Restart Nginx
        uses: appleboy/ssh-action@v1.0.3
        with:
          host: ${{ secrets.VPS_HOST }}
          username: ${{ secrets.VPS_USER }}
          key: ${{ secrets.VPS_SSH_KEY }}
          script: |
            chown -R www-data:www-data /var/www/shinelogics-frontend
            chmod -R 755 /var/www/shinelogics-frontend
            systemctl restart nginx
